# Energy Pebble - Main Configuration
esphome:
  name: energy-pebble
  friendly_name: Energy Pebble
  project:
    name: "thomaskgb.energy-pebble"
    version: !env_var version
  # Disable safe mode to prevent unexpected behavior
  on_boot:
    priority: 600
    then:
      - logger.log: 
          level: INFO
          format: "Energy Pebble booted successfully"
      - script.execute: boot_led_sequence
      - delay: 5s
      - logger.log: 
          level: INFO
          format: "Boot delay completed - system stable"
      - script.execute: simple_api_call

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino

# Explicitly configure preferences to ensure WiFi credentials persist
preferences:
  flash_write_interval: 5min

# Enable logging with reduced verbosity to prevent log spam
logger:
  level: DEBUG
  logs:
    component: ERROR
    web_server: ERROR
    light: ERROR  # Silence verbose LED logging
    esp32_rmt_led_strip: ERROR

# Time component for synchronization
time:
  - platform: sntp
    id: system_time

# Include all component configuration
packages:
  connectivity: !include components/connectivity.yaml
  leds: !include components/leds.yaml
  api: !include components/api.yaml
  boot: !include components/boot.yaml
  ota: !include components/ota.yaml
  # controls: !include components/controls.yaml