# Energy Pebble - Main Configuration
esphome:
  name: energy-pebble
  friendly_name: Energy Pebble
  # Disable safe mode to prevent unexpected behavior
  on_boot:
    priority: 600
    then:
      - logger.log: "Energy Pebble booted successfully"
      - delay: 5s
      - logger.log: "Boot delay completed - system stable"
          
esp32:
  board: lolin_c3_mini
  framework:
    type: arduino

# Enable logging with reduced verbosity to prevent log spam
logger:
  level: DEBUG
  logs:
    component: ERROR
    web_server: ERROR
    light: ERROR  # Silence verbose LED logging
    esp32_rmt_led_strip: ERROR

# Time component for synchronization
time:
  - platform: sntp
    id: system_time

# Include all component configuration
packages:
  connectivity: !include components/connectivity.yaml
  leds: !include components/leds.yaml
  api: !include components/api.yaml
  # controls: !include components/controls.yaml