esphome:
  name: neopixel-ring-demo
  friendly_name: "NeoPixel Ring Demo"
  on_boot:
    - priority: 800
      then:
        - light.turn_on:
            id: led_ring
            brightness: 100%
            red: 100%
            green: 100%
            blue: 100%

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

logger:

light:
  - platform: esp32_rmt_led_strip
    id: led_ring
    name: "NeoPixel Ring"
    chipset: ws2812
    pin: GPIO06        # Change this if you use a different data pin
    num_leds: 24
    rgb_order: GRB
    rmt_channel: 0

