# Button to manually refresh
binary_sensor:
  - platform: gpio
    pin: 
      number: GPIO2  # Change this to the button pin on your C3 Mini
      mode: INPUT_PULLUP
    name: "Refresh Button"
    icon: "mdi:refresh"
    on_press:
      then:
        - logger.log: "Manual refresh triggered"
        - script.execute: fetch_color_data

# Switch to enable/disable automatic updates
switch:
  - platform: template
    name: "Auto Update"
    id: auto_update_switch
    icon: "mdi:autorenew"
    optimistic: true
    on_turn_on:
      then:
        - script.execute: start_auto_update
        - logger.log: "Auto update enabled"
    on_turn_off:
      then:
        - script.execute: stop_auto_update
        - logger.log: "Auto update disabled"

# Create scripts to start and stop the interval
script:
  - id: start_auto_update
    then:
      - lambda: |-
          id(api_update_interval).start();
  
  - id: stop_auto_update
    then:
      - lambda: |-
          id(api_update_interval).stop();

  - id: demo_mode
    then:
      - logger.log: "Demo mode activated"
      - light.turn_on:
          id: ring_leds
          effect: Rainbow
      - delay: 3s
      - light.turn_on:
          id: ring_leds
          effect: Color Wipe
      - delay: 3s
      - script.execute: update_display


# Button to trigger a demo mode
button:
  - platform: template
    name: "Demo Mode"
    icon: "mdi:movie-play"
    on_press:
      then:
        - script.execute: demo_mode
