name: Build and Deploy Firmware

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags like v1.2.0

env:
  ESPHOME_VERSION: "2024.6.0"

jobs:
  build-firmware:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repo
        uses: actions/checkout@v4
        
      - name: Extract version from tag
        id: version
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
          echo "Building version: ${VERSION}"
          
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install ESPHome
        run: |
          pip install esphome==2025.6.0
          
      - name: Create secrets files
        run: |
          # Create secrets.yaml from environment variables (for CI)
          cat > secrets.yaml << EOF
          # WiFi credentials
          wifi_ssid: "${{ secrets.WIFI_SSID || 'YOUR_WIFI_SSID' }}"
          wifi_password: "${{ secrets.WIFI_PASSWORD || 'YOUR_WIFI_PASSWORD' }}"

          # Security
          ota_password: "${{ secrets.OTA_PASSWORD || 'YOUR_OTA_PASSWORD' }}"
          EOF
          
          # Create components/secrets.yaml with same content  
          cp secrets.yaml components/secrets.yaml
          
      - name: Build firmware
        env:
          version: ${{ steps.version.outputs.version }}
        run: |
          esphome compile energy_pebble.yaml
            
      - name: Prepare firmware files
        id: prepare
        run: |
          mkdir -p firmware
          cp .esphome/build/energy-pebble/.pioenvs/energy-pebble/firmware.ota.bin \
            firmware/energy-pebble-${{ steps.version.outputs.version }}.bin
          
          # Calculate MD5 and SHA-256 hashes of the firmware binary
          MD5_HASH=$(md5sum firmware/energy-pebble-${{ steps.version.outputs.version }}.bin | cut -d' ' -f1)
          SHA256_HASH=$(sha256sum firmware/energy-pebble-${{ steps.version.outputs.version }}.bin | cut -d' ' -f1)
          echo "md5_hash=${MD5_HASH}" >> $GITHUB_OUTPUT
          echo "sha256_hash=${SHA256_HASH}" >> $GITHUB_OUTPUT
          echo "Firmware MD5: ${MD5_HASH}"
          echo "Firmware SHA-256: ${SHA256_HASH}"
          
          # List what we have for debugging
          ls -la .esphome/build/energy-pebble/.pioenvs/energy-pebble/
          echo "Firmware build completed successfully!"
            
      - name: Upload firmware via API
        run: |
          # Upload firmware to the API server using correct parameters
          curl -X POST "https://energypebble.tdlx.nl/api/firmware/upload" \
            -H "Authorization: Bearer ${{ secrets.API_ADMIN_TOKEN }}" \
            -H "accept: application/json" \
            -H "Content-Type: multipart/form-data" \
            -F "firmware_file=@firmware/energy-pebble-${{ steps.version.outputs.version }}.bin;type=application/octet-stream" \
            -F "version=v${{ steps.version.outputs.version }}" \
            -F "product_name=energy_pebble" \
            -F "variant=release" \
            -F "is_stable=true" \
            -F "release_notes=$(git log -1 --pretty=format:'%s')" \
            -F "min_version=" \
            -F "target_devices=" \
            -F "force_update=false" \
            -F "rollback_version=" \
            -F "md5_hash=${{ steps.prepare.outputs.md5_hash }}" \
            -F "sha256_hash=${{ steps.prepare.outputs.sha256_hash }}" \
            --fail-with-body \
            -v